 - name: PLAY 01
   hosts: local
   connections: local
   tasks:
    - name : PLAY 01 and TASK 01
      ansible.builtin.debug:
        msg: "hello from PLAY 01 and TASK 01"

    - name : PLAY 01 and TASK 02
      ansible.builtin.debug:
        msg: "hello from PLAY 01 and TASK 02"

 - name:  PLAY 02
   hosts: local
   connections: local
   tasks:
    - name: PLAY 02 and TASK 02
      ansible.builtin.debug:
      msg: "hello from PLAY 02 and TASK 02"